### PR TITLE
fix: bunny consumer message metadata

### PR DESCRIPTION
**Pull request by ireznice**

### CODE REVIEW

**Comment by lksv** [comment]
LGTM :+1: 

Unfortunately tests are falling. The problem is, that:
`Gem::InstallError: amq-protocol requires Ruby version >= 2.0.`

Maybe installing older version of bunny in ruby mvr 1.9.3 environment in `travis.yml` should fix it (`gem install bunny --version "=..."`).

**Comment by ireznice** [comment]
Fixed, added mri 2.2.2 as well

**Comment by lksv** [comment]
This solution prohibits usage newer version even on new mri.
Keep it free in Gemfile. But use custom Gemfile in travis test (or maybe
the version of bunny could be set by env variable).

See
https://docs.travis-ci.com/user/languages/ruby#Custom-Bundler-arguments-and-Gemfile-locations
and
https://docs.travis-ci.com/user/languages/ruby#Testing-against-multiple-versions-of-dependencies

On Thu, Jan 28, 2016 at 9:12 AM, ireznice notifications@github.com wrote:

> Fixed, added mri 2.2.2 as well
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/final-ci/travis-support/pull/2#issuecomment-176046671
> .

## 

Lukas Svoboda

**Comment by lksv** [comment]
:+1:

**Pull request merged**
